version: '3'

services:

  mofukaze:
    build:
      context: ./mofukaze
      dockerfile: Dockerfile
    container_name: mofukaze
    expose:
      - "3000"
    environment:
      API_GATEWAY_URL: "http://api_gateway:3001"
      NODE_ENV: production
    depends_on:
      - api_gateway
    networks:
      - app-network
    volumes:
      - ./resource_service/resources:/resources  # 挂载资源共享目录

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    expose:
      - "3001"
    environment:
      BLOG_SERVICE_URL: "http://blog_service:3002"
      NODE_ENV: production
    depends_on:
      - blog_service
    networks:
      - app-network
    volumes:
      - ./resource_service/resources:/resources  # 同样挂载

  blog_service:
    build:
      context: ./blog_service
      dockerfile: Dockerfile
    container_name: blog_service
    expose:
      - "3002"
    environment:
      NODE_ENV: production
    networks:
      - app-network
    volumes:
      - ./resource_service/resources:/resources  # 同样挂载

  resource_service:
    build:
      context: ./resource_service
      dockerfile: Dockerfile
    container_name: resource_service
    ports:
      - "8081:8081"
    volumes:
      - ./resource_service/resources:/resources
    networks:
      - app-network

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./mofukaze/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resource_service/resources:/resources  # nginx 也能访问
    depends_on:
      - mofukaze
      - api_gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
